version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_STANDARD_USER: ${MYSQL_STANDARD_USER}
      MYSQL_STANDARD_PASSWORD: ${MYSQL_STANDARD_PASSWORD}
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_STANDARD_USER: ${MYSQL_STANDARD_USER}
      MYSQL_STANDARD_PASSWORD: ${MYSQL_STANDARD_PASSWORD}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443" # it is the only port exposed to the internet as it is mapped with port 443 of the host machine
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker-network

volumes:
  mariadb_data: 
    driver: local
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/ikgonzal/data/mysql
      o: bind
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/ikgonzal/data/wordpress
      o: bind

networks:
  docker-network:
    name: docker-network
