version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306" # only expose within the Docker network. Not mapping to host machine port
    env_file:
      - .env
    volumes:
      - mariadb-data:/home/ikgonzal/data
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080" # only expose within the Docker network. Not mapping to host machine port
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/home/ikgonzal/data
    networks:
      - docker-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443" # it is the only port exposed to the internet as it is mapped with port 443 of the host machine
    depends_on:
      - wordpress
    networks:
      - docker-network

volumes:
  mariadb-data:
  wordpress-data:

networks:
  docker-network:
