version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_STANDARD_USER: ${MYSQL_STANDARD_USER}
      MYSQL_STANDARD_PASSWORD: ${MYSQL_STANDARD_PASSWORD}
    ports:
      - "3306" # only expose within the Docker network. Not mapping to host machine port
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_STANDARD_USER: ${MYSQL_STANDARD_USER}
      MYSQL_STANDARD_PASSWORD: ${MYSQL_STANDARD_PASSWORD}
    ports:
      - "9000" # only expose within the Docker network. Not mapping to host machine port
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - docker-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443" # it is the only port exposed to the internet as it is mapped with port 443 of the host machine
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - docker-network

volumes:
  mariadb_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/ikgonzal/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ikgonzal/data/wordpress
      o: bind

networks:
  docker-network:
